config/routes.rb
Rails.application.routes.draw do
  resources :properties
  resources :posts
  get 'welcome/about'

  get 'welcome/index'

  devise_for :users
  resources :comments do
    collection do
      get :get_comment
    end
  end

  resources :meals

  resources :scheduled_events

  resources :events do
    resources :comments
  end

  resources :schedules

  root 'posts#index'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  has_many :scheduled_events
  has_many :events, through: :scheduled_events
  belongs_to :user
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = current_user.schedules
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = current_user.schedules.build(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = current_user.schedules.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:name)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<style>
  td { border: 0 dashed red; vertical-align: top; }
  ul { padding: 1em 1em 1em 1em; margin: 0; list-style-type:none; }
  li { line-height: 2em; font-size: medium; }
  h2 { display: inline-block; margin-right: 1em; }
  th { padding: .5em; font-size: medium; }
</style>

<h1>Listing schedules</h1>

<% @schedules.each do |schedule| %>
  <h2><%= schedule.name %></h2>
  <%= link_to 'Show', schedule %>
  <%= link_to 'Edit', edit_schedule_path(schedule) %>
  <%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %>
  <table style="margin-left: auto; margin-right: auto;">
    <thead>
      <% day = Date.today.strftime('%A') %>
      <th style="<%= 'color: #DD6600;' if day == 'Monday' %>">Monday</th>
      <th style="<%= 'color: teal;' if day == 'Tuesday' %>">Tuesday</th>
      <th style="<%= 'color: #DD6600;' if day == 'Wednesday' %>">Wednesday</th>
      <th style="<%= 'color: #DD6600;' if day == 'Thursday' %>">Thursday</th>
      <th style="<%= 'color: #DD6600;' if day == 'Friday' %>">Friday</th>
      <th style="<%= 'color: #DD6600;' if day == 'Saturday' %>">Saturday</th>
      <th style="<%= 'color: #DD6600;' if day == 'Sunday' %>">Sunday</th>
    </thead>
    <tbody>
      <tr>
        <td>
          <ul>
            <% schedule.scheduled_events.where(day: 'mon').each do |event| %>
              <li><%= link_to event.event.name, event.event %></li>
            <% end %>
          </ul>
        </td>
        <td>
          <ul>
            <% schedule.scheduled_events.where(day: 'tue').each do |event| %>
              <li><%= link_to event.event.name, event.event %></li>
            <% end %>
          </ul>
        </td>
        <td>
          <ul>
            <% schedule.scheduled_events.where(day: 'wed').each do |event| %>
              <li><%= link_to event.event.name, event.event %></li>
            <% end %>
          </ul>
        </td>
        <td>
          <ul>
            <% schedule.scheduled_events.where(day: 'thu').each do |event| %>
              <li><%= link_to event.event.name, event.event %></li>
            <% end %>
          </ul>
        </td>
        <td>
          <ul>
            <% schedule.scheduled_events.where(day: 'fri').each do |event| %>
              <li><%= link_to event.event.name, event.event %></li>
            <% end %>
          </ul>
        </td>
        <td>
          <ul>
            <% schedule.scheduled_events.where(day: 'sat').each do |event| %>
              <li><%= link_to event.event.name, event.event %></li>
            <% end %>
          </ul>
        </td>
        <td>
          <ul>
            <% schedule.scheduled_events.where(day: 'sun').each do |event| %>
              <li><%= link_to event.event.name, event.event %></li>
            <% end %>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

<br>

<%= link_to 'New Schedule', new_schedule_path %> |
<%= link_to 'New Scheduled Event',
  '#',
  :id => "scheduled_event_form_revealer",
  :class => 'fake_link'
%>
<% @scheduled_event = ScheduledEvent.new %>
<div id="scheduled_event_form_container" style="display: none;">
  <%= render :partial=>'scheduled_events/form' %>
</div>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<style>
  td { border: 0 dashed red; vertical-align: top; }
  ul { padding: 0 1em 0 2em; margin: 0; }
</style>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @schedule.name %>
</p>
<table>
  <thead>
    <th>Mon</th>
    <th>Tue</th>
    <th>Wed</th>
    <th>Thu</th>
    <th>Fri</th>
    <th>Sat</th>
    <th>Sun</th>
  </thead>
  <tbody>
    <tr>
      <td>
        <ul>
          <% @schedule.scheduled_events.where(day: 'mon').each do |event| %>
            <li><%= event.event.name %></li>
          <% end %>
        </ul>
      </td>
      <td>
        <ul>
          <% @schedule.scheduled_events.where(day: 'tue').each do |event| %>
            <li><%= event.event.name %></li>
          <% end %>
        </ul>
      </td>
      <td>
        <ul>
          <% @schedule.scheduled_events.where(day: 'wed').each do |event| %>
            <li><%= event.event.name %></li>
          <% end %>
        </ul>
      </td>
      <td>
        <ul>
          <% @schedule.scheduled_events.where(day: 'thu').each do |event| %>
            <li><%= event.event.name %></li>
          <% end %>
        </ul>
      </td>
      <td>
        <ul>
          <% @schedule.scheduled_events.where(day: 'fri').each do |event| %>
            <li><%= event.event.name %></li>
          <% end %>
        </ul>
      </td>
      <td>
        <ul>
          <% @schedule.scheduled_events.where(day: 'sat').each do |event| %>
            <li><%= event.event.name %></li>
          <% end %>
        </ul>
      </td>
      <td>
        <ul>
          <% @schedule.scheduled_events.where(day: 'sun').each do |event| %>
            <li><%= event.event.name %></li>
          <% end %>
        </ul>
      </td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>