config/routes.rb
Rails.application.routes.draw do
  resources :properties
  resources :posts
  get 'welcome/about'

  get 'welcome/index'

  devise_for :users
  resources :comments do
    collection do
      get :get_comment
    end
  end

  resources :meals

  resources :scheduled_events

  resources :events do
    resources :comments
  end

  resources :schedules

  root 'posts#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  acts_as_commentable
  has_many :scheduled_events
  has_many :schedules, through: :scheduled_events
  belongs_to :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = current_user.events
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = current_user.events.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<style>
  td { padding: 1em; vertical-align: top; }
  td.commentable_link a { font-size: medium; }
  td.comment { line-height: 1.5em; }
  td.comment_actions a { font-size: x-small; }
  td p { padding-top: 0; margin-top: 0; }
</style>
<p id="notice"><%= notice %></p>

<h1><%= @event.name %></h1>

<div style="text-align: right; width: 500px; margin-left: auto; margin-right: auto;">
  <%= form_for [@event, Comment.new] do |f| %>
    <%= f.text_area :comment, :style=>'width: 100%' %>
    <%= f.hidden_field :commentable_id, :value=>@event.id %>
    <%= f.hidden_field :commentable_type, :value=>@event.class.name %>
    <%= f.submit %>
  <% end %>
</div>

<table style="margin-left: auto; margin-right: auto;">
  <% @event.comments.all.each do |comment| %>
    <tr>
      <% day = nil %>
      <td style="white-space: nowrap; font-size: medium;">
        <% unless day == comment.created_at.strftime('%A') %>
          <% day = comment.created_at.strftime('%A') %>
           <%= comment.created_at.strftime('%a, %b %d, %Y') %>
        <% end %>
      </td>
      <td style="font-size: medium; white-space: nowrap;">
        <%= comment.created_at.strftime('%-I:%M %p') %>
      </td>
      <td class="comment" style="max-width: 500px;"><%= simple_format(comment.comment) %></td>
      <td class="comment_actions" style="white-space: nowrap;">
        <%= link_to 'Show', comment %> |
        <%= link_to 'Edit', edit_comment_path(comment) %> |
        <%= link_to 'Destroy', comment_path(comment, :return_path=>event_path(@event)), method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', schedules_path %>