config/routes.rb
Rails.application.routes.draw do
  resources :properties
  resources :posts
  get 'welcome/about'

  get 'welcome/index'

  devise_for :users
  resources :comments do
    collection do
      get :get_comment
    end
  end

  resources :meals

  resources :scheduled_events

  resources :events do
    resources :comments
  end

  resources :schedules

  root 'posts#index'

end

app/models/scheduled_event.rb
class ScheduledEvent < ActiveRecord::Base
  belongs_to :schedule
  belongs_to :event
  belongs_to :user
end

app/controllers/scheduled_events_controller.rb
class ScheduledEventsController < ApplicationController
  before_action :set_scheduled_event, only: [:show, :edit, :update, :destroy]

  # GET /scheduled_events
  # GET /scheduled_events.json
  def index
    @scheduled_events = current_user.scheduled_events.all
  end

  # GET /scheduled_events/1
  # GET /scheduled_events/1.json
  def show
  end

  # GET /scheduled_events/new
  def new
    @scheduled_event = ScheduledEvent.new
  end

  # GET /scheduled_events/1/edit
  def edit
  end

  # POST /scheduled_events
  # POST /scheduled_events.json
  def create
    @scheduled_event = current_user.scheduled_events.build(scheduled_event_params)

    respond_to do |format|
      if @scheduled_event.save
        format.html { redirect_to @scheduled_event, notice: 'Scheduled event was successfully created.' }
        format.json { render :show, status: :created, location: @scheduled_event }
      else
        format.html { render :new }
        format.json { render json: @scheduled_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scheduled_events/1
  # PATCH/PUT /scheduled_events/1.json
  def update
    respond_to do |format|
      if @scheduled_event.update(scheduled_event_params)
        format.html { redirect_to @scheduled_event, notice: 'Scheduled event was successfully updated.' }
        format.json { render :show, status: :ok, location: @scheduled_event }
      else
        format.html { render :edit }
        format.json { render json: @scheduled_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scheduled_events/1
  # DELETE /scheduled_events/1.json
  def destroy
    @scheduled_event.destroy
    respond_to do |format|
      format.html { redirect_to scheduled_events_url, notice: 'Scheduled event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scheduled_event
      @scheduled_event = current_user.scheduled_events.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scheduled_event_params
      params.require(:scheduled_event).permit(:day, :schedule_id, :event_id)
    end
end

app/helpers/scheduled_events_helper.rb
module ScheduledEventsHelper
end

app/views/scheduled_events/_form.html.erb
<%= form_for(@scheduled_event) do |f| %>
  <% if @scheduled_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scheduled_event.errors.count, "error") %> prohibited this scheduled_event from being saved:</h2>

      <ul>
      <% @scheduled_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br>
    <%= f.select :day, [['Mon', 'mon'], ['Tue', 'tue'], ['Wed', 'wed'], ['Thu', 'thu'], ['Fri', 'fri'], ['Sat', 'sat'], ['Sun', 'sun']] %><br>
  </div>
  <div class="field">
    <%= f.label :schedule %><br>
    <%= f.select :schedule_id, current_user.schedules.map{ |s| [s.name, s.id] } %>
  </div>
  <div class="field">
    <%= f.label :event %><br>
    <%= f.select :event_id, current_user.events.map{ |e| [e.name, e.id] } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scheduled_events/edit.html.erb
<h1>Editing scheduled_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @scheduled_event %> |
<%= link_to 'Back', scheduled_events_path %>

app/views/scheduled_events/index.html.erb
<h1>Listing scheduled_events</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Event</th>
      <th>Schedule</th>
    </tr>
  </thead>

  <tbody>
    <% @scheduled_events.each do |scheduled_event| %>
      <tr>
        <td><%= scheduled_event.day %></td>
        <td><%= scheduled_event.event.name if scheduled_event.event %></td>
        <td><%= scheduled_event.schedule.name if scheduled_event.schedule %></td>
        <td><%= link_to 'Show', scheduled_event %></td>
        <td><%= link_to 'Edit', edit_scheduled_event_path(scheduled_event) %></td>
        <td><%= link_to 'Destroy', scheduled_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scheduled event', new_scheduled_event_path %>

app/views/scheduled_events/new.html.erb
<h1>New scheduled_event</h1>

<%= render 'form' %>

<%= link_to 'Back', scheduled_events_path %>

app/views/scheduled_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @scheduled_event.day %>
</p>

<%= link_to 'Edit', edit_scheduled_event_path(@scheduled_event) %> |
<%= link_to 'Back', scheduled_events_path %>