config/routes.rb
Rails.application.routes.draw do
  resources :properties
  resources :posts
  get 'welcome/about'

  get 'welcome/index'

  devise_for :users
  resources :comments do
    collection do
      get :get_comment
    end
  end

  resources :meals

  resources :scheduled_events

  resources :events do
    resources :comments
  end

  resources :schedules

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter :authenticate_user!
  before_action :set_post, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order('created_at DESC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_user.posts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post, { html: { style: 'max-width: 800px' }}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %>
        prohibited this post from being saved:
      </h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, style: "width: 100%;" %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, style: "width: 100%; height: 500px;" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render :partial => 'welcome/header', :locals => { :css_class => 'grid header' } %>
<p id="notice"><%= notice %></p>

<div class="grid grid-pad">
  <% if user_signed_in? %>
    <div class="col-8-12">
      <%= link_to 'New Post', new_post_path, :style => 'float: right;' %>
    </div>
  <% end %>
  <div class="col-4-12" style="float: right;">
    <h2 style="text-align: center; margin-bottom: 2em">Sample Work</h2>
    <%= to_markdown(prop('WelcomeContent')) %>
  </div>
  <% @posts.each do |post| %>
    <div class="col-8-12" style="margin-bottom: 4em;">
      <% if user_signed_in? && current_user.posts.find_by_id(post.id) %>
        <div style="text-align: right;">
          <%= link_to 'Edit', edit_post_path(post) %>
          <%= link_to 'Destroy',
            post,
            method: :delete,
            data: { confirm: 'Are you sure?' }
          %>
        </div>
      <% end %>
      <h1 style="text-align: center;"><%= post.title %></h1>
      <p style="padding-bottom: 10px; text-align: center;">
        published: <%= post.created_at.to_date.strftime('%a, %b %d, %Y') %>
        <br />
        by: <%= post.user.email.gsub(/@.*/, '') %>
      </p>
      <%= to_markdown(post.body.truncate(400)) %>
      <% if post.body.length > 400 %>
        <h3 style="float: right; margin: 0; padding: 0;">
          <%= link_to 'Continue reading...', post %>
        </h3>
      <% end %>
    </div>
  <% end %>
</div>

<div class="grid footer">
  <div class="col-2-12">
    <h3><%= link_to 'About', welcome_about_path %></h3>
  </div>
  <div class="col-2-12">
    <h3><%= link_to 'Sign In', new_user_session_path %></h3>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.slim
p id="notice" = notice
.grid.grid-pad
  .col-8-12
    - if user_signed_in? && current_user.posts.find_by_id(@post.id)
      div style="float: right;"
        => link_to 'Edit', edit_post_path(@post)
        = link_to 'Destroy',
          @post,
          method: :delete,
          data: { confirm: 'Are you sure?' }
    = link_to 'Back', posts_path
    h1 style="text-align: center;" = @post.title
    p style="padding-bottom: 10px; text-align: center;"
      ' published:
      = @post.created_at.to_date.strftime('%a, %b %d, %Y')
      br
      ' by:
      = @post.user.email.gsub(/@.*/, '')
    = to_markdown(@post.body)
.grid.footer
  .col-2-12
    h3 = link_to 'Main', root_path
  .col-2-12
    h3 = link_to 'Sign In', new_user_session_path